import type { Product } from '@/types'

export const mockProducts: Product[] = [
  {
    id: '1',
    name: 'שוקולד בלגי פרימיום',
    description_short: 'שוקולד בלגי שחור 70% קקאו באריזת מתנה',
    description_full: 'שוקולד בלגי פרימיום 70% קקאו, אריזת מתנה יפהפייה המתאימה לכל אירוע. יוצר ב-Belgian בבלגיה ומיוצא ישירות.',
    sku: 'CHOC-001',
    category: 'chocolates',
    tags: ['שוקולד', 'בלגי', 'פרימיום', 'מתנה'],
    price_store: 28,
    price_retail: 55,
    profit_per_unit: 27,
    profit_percent: 49,
    moq: 12,
    stock_quantity: 240,
    carton_qty: 24,
    brand: 'Belgian Premium',
    suitable_for: ['flowers', 'gift_sets', 'newborn', 'birthday'],
    images: [],
    is_new: false,
    is_featured: true,
    is_top_seller: true,
    is_seasonal: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '2',
    name: 'יין אדום בוטיק "גבעות"',
    description_short: 'יין אדום בוטיק ישראלי, יבול 2021',
    description_full: 'יין אדום בוטיק מגפן ישראלית נבחרת, יבול 2021. טעמים עמוקים של פירות יער ואורן, סיום ארוך.',
    sku: 'WINE-001',
    category: 'wines',
    tags: ['יין', 'אדום', 'בוטיק', 'ישראלי'],
    price_store: 65,
    price_retail: 120,
    profit_per_unit: 55,
    profit_percent: 46,
    moq: 6,
    stock_quantity: 120,
    carton_qty: 6,
    brand: 'גבעות',
    suitable_for: ['gift_sets', 'catering', 'corporate'],
    images: [],
    is_new: false,
    is_featured: true,
    is_top_seller: true,
    is_seasonal: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '3',
    name: 'מארז מתנה יוקרה',
    description_short: 'מארז כולל שוקולד, תה ועוגיות בקופסת עץ',
    description_full: 'מארז מתנה יוקרתי בקופסת עץ ממוחזרת. כולל שוקולד בלגי, תה פרמיום ועוגיות חמאה. מושלם לאירועים ועסקים.',
    sku: 'GIFT-001',
    category: 'gift_sets',
    tags: ['מארז', 'מתנה', 'יוקרה', 'עסקי'],
    price_store: 85,
    price_retail: 160,
    profit_per_unit: 75,
    profit_percent: 47,
    moq: 6,
    stock_quantity: 80,
    carton_qty: 6,
    brand: 'VAZA Collection',
    suitable_for: ['flowers', 'gift_sets', 'catering', 'corporate', 'employees'],
    images: [],
    is_new: true,
    is_featured: true,
    is_top_seller: false,
    is_seasonal: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '4',
    name: 'תה פרמיום אנגלי',
    description_short: 'קולקציית תה פרמיום 20 שקיות',
    description_full: 'קולקציית תה פרמיום מאנגליה, 20 שקיות בטעמים שונים. אריזה מהודרת המתאימה כמתנה.',
    sku: 'TEA-001',
    category: 'tea',
    tags: ['תה', 'אנגלי', 'פרמיום'],
    price_store: 32,
    price_retail: 65,
    profit_per_unit: 33,
    profit_percent: 51,
    moq: 12,
    stock_quantity: 180,
    carton_qty: 12,
    brand: 'English Premium',
    suitable_for: ['gift_sets', 'catering', 'corporate'],
    images: [],
    is_new: false,
    is_featured: false,
    is_top_seller: true,
    is_seasonal: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '5',
    name: 'עוגיות חמאה דנית',
    description_short: 'עוגיות חמאה דנית קלאסיות בפחית מתנה',
    description_full: 'עוגיות חמאה דנית קלאסיות בפחית מתנה מיוחדת. מושלמות לחגים ואירועים.',
    sku: 'COOK-001',
    category: 'cookies',
    tags: ['עוגיות', 'דניות', 'חמאה', 'חג'],
    price_store: 42,
    price_retail: 85,
    profit_per_unit: 43,
    profit_percent: 51,
    moq: 12,
    stock_quantity: 150,
    carton_qty: 12,
    brand: 'Danish Classic',
    suitable_for: ['gift_sets', 'catering', 'employees'],
    images: [],
    is_new: false,
    is_featured: false,
    is_top_seller: true,
    is_seasonal: true,
    season: 'holidays',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '6',
    name: 'שמפניה ולנטיין',
    description_short: 'שמפניה פרנסואה קרניאר עם מארז ולנטיין',
    description_full: 'שמפניה פרנסואה קרניאר בקבוק 750מ"ל עם מארז ולנטיין כולל שוקולדים בצורת לב.',
    sku: 'VAL-001',
    category: 'valentines',
    tags: ['ולנטיין', 'שמפניה', 'רומנטי', 'ט"ו באב'],
    price_store: 95,
    price_retail: 190,
    profit_per_unit: 95,
    profit_percent: 50,
    moq: 6,
    stock_quantity: 60,
    carton_qty: 6,
    brand: 'Love Collection',
    suitable_for: ['flowers', 'romantic', 'gift_sets'],
    images: [],
    is_new: false,
    is_featured: true,
    is_top_seller: false,
    is_seasonal: true,
    season: 'valentines',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
]
